spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/web16?rewriteBatchedStatements=true
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false 
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true